# GitHub Actions workflow for deploying React app to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Trigger on push to master branch
  push:
    branches: [ main ]
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

# Set permissions for GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

          
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
        
      - name: Build project
        run: npm run build
        working-directory: frontend
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'

  # Expo Android build job
  expo-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Expo CLI
        run: npm install @expo/cli
        working-directory: expojs
      - name: Install dependencies
        run: npm ci
        working-directory: expojs
      - name: Install EAS CLI
        run: npm install -g eas-cli
        working-directory: expojs
      - name: Build Android APK
        run: eas build --platform android --profile development
        working-directory: expojs
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: expojs/dist/*.apk

  release:
    runs-on: ubuntu-latest
    needs: [build, expo-android]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for semantic release
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts/
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: steps.release.outputs.release_created
        with:
          files: |
            artifacts/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
